### ISSUE TITLE
Sponsor donation page

### ISSUE THREAD

**Issue by Andersos** [webrebels/web-rebels-2016#19]
As a sponsor I want a page that I can submit an extra sponsor amount for the scholarship.

We should try and use our Stripe account for this

**Comment by leftieFriele** [comment]
I've completed a first shot at this in the 'donate' branch.
there's some things like validation and user confirmation and things... but it works now. These are the routes I've added in the donations module.
GET /scholarship/donate
POST /scholarship/donate
GET /scholarship/dontaions

**Comment by Andersos** [comment]
Sweet. Good job =)

**Comment by leftieFriele** [comment]
I think we should launch this the day we announce tickets sales dates. That'll give this a lot of attention... I think..

**Comment by Andersos** [comment]
We had a lot extra this year considering it was 3 conferences. We will have to revive the Scholarships for next year.
