### ISSUE TITLE
Configure and setup tito.io for WR ticketing

### ISSUE THREAD

**Issue by leftieFriele** [webrebels/web-rebels-2016#4]

**Comment by leftieFriele** [comment]
The account is setup, but we need to create tickets and things. You fix @Andersos  :)

**Comment by Andersos** [comment]
Are you thinking about creating Web Rebels tickets in the tito account?

**Comment by leftieFriele** [comment]
Yes, scheduled times amounts price. Look into how to limit number of tickets per person. Things like that. 
Also look at the tito page for the conf to see if all info is there.

**Comment by Andersos** [comment]
- [ ] Check Tito page to see if all the info is there
- [ ] Figure out ticket price
- [ ] Figure out amount of tickets and when to sell them

**Comment by Andersos** [comment]
Done
