### ISSUE TITLE
Resolve the issue with GH pages not providing TLS

### ISSUE THREAD

**Issue by leftieFriele** [webrebels/web-rebels-2016#8]
Currently old sites are borked, because we redirect to https and GH pages doesn't support it. This sucks and we should make this work.
Either host the archived pages somewhere else or make the subdomains not use tls

**Comment by Andersos** [comment]
This might help https://www.benburwell.com/posts/configuring-cloudflare-universal-ssl/

**Comment by leftieFriele** [comment]
Even thought it's [not 100%](https://konklone.com/post/github-pages-now-supports-https-so-use-it#using-your-custom-domain), it's better than having the sites not work. 
I assume [this procedure](http://davidensinger.com/2014/04/transferring-the-dns-from-namecheap-to-cloudflare-for-github-pages/) should do it. However, it seems that we need to do [this](http://www.chrisanthropic.com/blog/2014/mail-forwarding-with-mailgun-and-cloudflare/) in order to make NameCheap email forwarding work when switching the DNS to Cloudflare

**Comment by leftieFriele** [comment]
I've added a pull request to resolve this without any additional services and things.

**Comment by leftieFriele** [comment]
I've made changes to the 2016 app to host the archives. What we're missing is a wildcard ssl cert

**Comment by trygve-lie** [comment]
Fixed in https://github.com/webrebels/web-rebels-archive
